### ISSUE TITLE
listFiles: casting exception 

### ISSUE THREAD

**Issue by albrechta** [Hive2Hive/Hive2Hive#127]
listFiles may throw a class cast exception because of a file / folder mismatch. 
```
java.lang.ClassCastException: org.hive2hive.core.model.FileIndex cannot be cast to org.hive2hive.core.model.FolderIndex
	at org.hive2hive.core.processes.files.list.GetFileListStep.copyTree(GetFileListStep.java:70) ~[classes/:na]
	at org.hive2hive.core.processes.files.list.GetFileListStep.copyTree(GetFileListStep.java:71) ~[classes/:na]
	at org.hive2hive.core.processes.files.list.GetFileListStep.doExecute(GetFileListStep.java:42) ~[classes/:na]
	at org.hive2hive.core.processes.files.list.GetFileListStep.doExecute(GetFileListStep.java:1) ~[classes/:na]
	at org.hive2hive.processframework.ProcessComponent.execute(ProcessComponent.java:70) ~[org.hive2hive.processframework-1.0.jar:na]
	at org.peerbox.app.manager.ProcessHandle.execute(ProcessHandle.java:27) ~[classes/:na]
	at org.peerbox.watchservice.filetree.FileTreeInitializer.initialize(FileTreeInitializer.java:41) ~[classes/:na]
	at org.peerbox.app.ClientContextFactory.create(ClientContextFactory.java:30) ~[classes/:na]
	at org.peerbox.presenter.LoginController.initializeServices(LoginController.java:309) [classes/:na]
	at org.peerbox.presenter.LoginController.onLoginSucceeded(LoginController.java:294) [classes/:na]
	at org.peerbox.presenter.LoginController.access$11(LoginController.java:286) [classes/:na]
	at org.peerbox.presenter.LoginController$5.handle(LoginController.java:266) [classes/:na]
	at org.peerbox.presenter.LoginController$5.handle(LoginController.java:1) [classes/:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219) [jfxrt.jar:na]
	at javafx.concurrent.Task.fireEvent(Task.java:1342) [jfxrt.jar:na]
	at javafx.concurrent.Task.setState(Task.java:720) [jfxrt.jar:na]
	at javafx.concurrent.Task$TaskCallable.lambda$call$443(Task.java:1420) [jfxrt.jar:na]
	at javafx.concurrent.Task$TaskCallable$$Lambda$276/265862762.run(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292) [jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl$$Lambda$52/1995016638.run(Unknown Source) [jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_25]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291) [jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl$$Lambda$51/1851691492.run(Unknown Source) [jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) [jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) [jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$45(GtkApplication.java:126) [jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$42/584634336.run(Unknown Source) [jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
```

Cannot reproduce yet.

**Comment by albrechta** [comment]
Problem is the following:
hash = null, and you assume that if the hash is null only for folders. But it may not be a folder and the hash may be null due to some other reason ("bug" in upload or profile modification).

What happened: we uploaded a file and it was deleted during the upload procedure due to a rename. This lead to hash = null somehow.
