### ISSUE TITLE
InvocationTargetException on Android

### ISSUE THREAD

**Issue by NoHarmDan** [Hive2Hive/Hive2Hive#157]
Hi, I wanted to experiment with Hive2Hive on Android, followed the instructions as stated at https://github.com/Hive2Hive/Hive2Hive/wiki/Android but calling `new FSTSerializer(false, new SCSecurityClassProvider())` crashes on an error I'm unable to comprehend. Please see the stack trace below. It fails on `classRegistry.registerClass(String.class);` which sounds pretty ridiculous to me - having trouble with the String class... What could possibly be the issue here?

```
 org.objenesis.ObjenesisException: java.lang.reflect.InvocationTargetException
        at org.objenesis.instantiator.android.Android18Instantiator.findConstructorIdForJavaLangObjectConstructor(Android18Instantiator.java:84)
        at org.objenesis.instantiator.android.Android18Instantiator.<init>(Android18Instantiator.java:39)
        at org.objenesis.strategy.StdInstantiatorStrategy.newInstantiatorOf(StdInstantiatorStrategy.java:86)
        at org.objenesis.ObjenesisBase.getInstantiatorOf(ObjenesisBase.java:91)
        at org.nustaq.serialization.FSTObjenesisInstantiator.<init>(FSTObjenesisInstantiator.java:38)
        at org.nustaq.serialization.FSTConfiguration$3.getInstantiator(FSTConfiguration.java:208)
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:108)
        at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:126)
        at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:91)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:78)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:74)
        at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:508)
        at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:237)
        at org.nustaq.serialization.FSTConfiguration.createAndroidDefaultConfiguration(FSTConfiguration.java:211)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:230)
        at org.hive2hive.core.serializer.FSTSerializer.<init>(FSTSerializer.java:66)
```

**Comment by NoHarmDan** [comment]
Ok, so the real culprit is Android Oreo, as found here: https://github.com/easymock/objenesis/issues/52

**Comment by NoHarmDan** [comment]
Solved by adding:
`implementation 'org.objenesis:objenesis:2.6'`
Which overrides the objenesis library used by Hive2Hive. Version 3.0.1 is available but requires minimal Android API to be 26, which is not an option.

**Comment by nicoruti** [comment]
Hi @NoHarmDan . Thanks for the report and clarification.
